config/routes.rb
Snowforest::Application.routes.draw do
  

  resources :users, :except => [:index]
  resources :sessions, :only => [:new, :create, :destroy]

  resources :products do
    resources :reviews, :except => [:index]
    resources :images 
  end

  root 'products#index'

end

app/models/image.rb
class Image < ActiveRecord::Base
  mount_uploader :path, ImageUploader
 
  belongs_to :product
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :reviews
  has_many :users, :through => :reviews
  has_many :images

  validates :description, :name, :presence => true
  validates :price_in_cents, :numericality => {:only_integer => true}

  accepts_nested_attributes_for :images 

  def formatted_price
    price_in_dollars = price_in_cents.to_f/100
    sprintf("%.2f", price_in_dollars)
  end

end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :product

  validates :comment, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base

  mount_uploader :avatar, AvatarUploader

  has_secure_password

  has_many :reviews
  has_many :products, :through => :reviews

  validates_presence_of :name

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def ensure_logged_in
    unless current_user
      flash[:alert] = "Please log in"
      redirect_to new_session_path
    end
  end

end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_filter :load_product

  def index

  end

  def new
    @image = Image.new
  end

  def create
    # @image = Image.new(
    #     :path => params[:image][:assets_attributes]["0"][:path],
    #     :product_id => @product_id
    #   )

    @image = @product.images.build(image_params)

    if @image.save
      redirect_to products_url, :notice => "Image Uploaded"
    else
      render "new"
    end
  end

  def show
    @image = Image.find(params[:image_id])
  end

  def destroy
    @image = Image.find(params[:image_id])
    @image.destroy
    redirect_to products_path, notice: "Image Deleted"
  end

  private 

  def image_params
    params.require(:image).permit(:product_id, :path)
  end

  def load_product
    @product = Product.find(params[:product_id])
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_filter :ensure_logged_in, :only => [:edit, :create, :destroy]

  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])

    if current_user
      @review = @product.reviews.build
      @image = @product.images.build
    end
  end

  def new
    @product = Product.new
  end

  def edit
    @product = Product.find(params[:id])
    # @product.images.build unless @product.images 
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to products_url
    else
      render :new
    end
  end

  def update
    @product = Product.find(params[:id])

    if @product.update_attributes(product_params)
      redirect_to product_path(@product)
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end

  private

  def product_params
    params.require(:product).permit(:name, :description, :price_in_cents, :images_attributes => [:path])
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_filter :load_product
  before_filter :ensure_logged_in, :only => [:edit, :create, :update, :destroy]


  def show
    @review = Review.find(params[:id])
  end

  def create
    @review = @product.reviews.build(review_params)
    @review.user_id = current_user.id
  
    # @review =  Review.new(
    #   :comment => params[:review][:comment],
    #   :product_id => @product.id,
    #   :user_id => current_user.id
    # )
#depreciated HTML non-AJAX code
    # if @review.save
    #   redirect_to products_path, notice: "Review created successfully"
    # else
    #   render :action => :show
    # end

    respond_to do |format|
      if @review.save
        format.html { redirect_to product_path(@product.id), notice: "Review created successfully."} #same as before
        format.js {} #create.js.erb
      else
        format.html { render 'products/show', alert: "Error in posting review." } #same as before
        format.js {} # create.js.erb
      end
    end

  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
  end

  private 

  def review_params
    params.require(:review).permit(:comment, :product_id)
  end

  def load_product
    @product = Product.find(params[:product_id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to products_url, :notice => "Logged in!"
    else
      flash.now[:alert] = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to products_url, :notice => "Logged Out!"
  end
end

# class SessionsController < ApplicationController
#   def new
#   end

#   def create
#     user = User.find_by_email(params[:email])
#     if user && user.authenticate(params[:password])
#       session[:user_id] = user.id
#       redirect_to products_url, :notice => "Logged in!"
#     else
#       render "new"
#     end
#   end

#   def destroy
#     session[:user_id] = nil
#     redirect_to products_url, :notice => "Logged out!"
#   end
# end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show 
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to products_url, :notice => "You're Signed Up!"
    else
      render "new"
    end
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(user_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to products_url, :notice => "User Deleted!"
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :name, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/images/create.html.erb
<h1>Images#create</h1>
<p>Find me in app/views/images/create.html.erb</p>

app/views/images/destroy.html.erb
<h1>Images#destroy</h1>
<p>Find me in app/views/images/destroy.html.erb</p>

app/views/images/index.html.erb
<h1>Images#index</h1>
<p>Find me in app/views/images/index.html.erb</p>

app/views/images/new.html.erb
<h1>Add an Image for your product</h1>

<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %> 
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <br><%= f.submit %>
  </div>
<% end %>

app/views/images/show.html.erb
<h1>Images#show</h1>
<p>Find me in app/views/images/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Snowforest</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="userinfo">
  <% if flash[:notice] %>  
    <p id='notice'><%= flash[:notice] %></p>
  <% end %>
  <% if flash[:alert] %>
    <p id="alert"><%= flash[:alert] %></p>
  <% end %>

  <p class="userstatus">
    <% if current_user %>
      Signed in as <%= link_to current_user.name, "/users/#{current_user.id}" %> <%= link_to "Log Out", session_path("current"), :method => :delete %>
    <% else %>
      <%= link_to "Log In", new_session_path %> or <%= link_to "Sign Up", new_user_path %>
    <% end %>
  </p>
</div>

<div class="header"> <h1>This is not <img src="http://blog.cmbinfo.com/Portals/75217/images/Amazon-Logo.png"></h1> </div>

<div id="content">
  <%= yield %>
</div>

</body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %> 
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %> 
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price_in_cents %>
    <%= f.number_field :price_in_cents %>
  </div>
  <div class="actions">
    <br><%= f.submit %>
  </div>
<% end %>

app/views/products/_image.html.erb
<% @product.images.each do |image| %>
  <p>      
  <%=image_tag(image.path)%>
  </p>
<% end %>

app/views/products/_newimage.html.erb
<%= form_for([@product, @image]) do |f| %>
  <% if @image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
      <% @image.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :path %><br />
      <%= f.file_field :path %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>

app/views/products/_newreview.html.erb
<%= form_for [@product, @review], :remote => true do |f| %>
    <% if @review.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

        <ul>
        <% @review.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
          </ul>
        </div>
      <% end %>
      <div class="field">
        <%= f.label :comment %><br />
        <%= f.text_area :comment %>
      </div>
      <div class="actions">
        <%= f.submit %>
      </div>
    <% end %>

app/views/products/_review.html.erb
<% @product.reviews.each do |review| %>
  <div class ="review">
    <p class = "comment">
      <%= review.comment %>
    </p>
    <div class="poster">
      <% if review.user !=nil %>
        <em> by <%= review.user.name %></em> on: <%= review.created_at %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/products/_reviewerror.html.erb
<%= form_for [@product, @review], :remote => true do |f| %>
    <% if @review.errors.present? %>
      <% @review.errors.full_messages.each do |error| %>
        <div class="alert">
          <%= error %>
        </div>
      <% end %>
    <% end %>
<% end %>

app/views/products/edit.html.erb
<h1>Edit Products</h1>

<%= link_to "Back to Products Index", products_url %>

<p><%= render 'form' %></p>

app/views/products/index.html.erb
<div class="menu">
  <%= link_to "+  Add a New Product", new_product_path %>
</div>

<ul>
<% @products.each do |product| %>
<div class="product">
  <li> <%= link_to product.name.upcase, product_path(product) %></br>
    $<%= product.formatted_price %></li>
  <%= image_tag(product.images.first.path.url) if product.images.count > 0 %>

</div>
<% end %>

</ul>

app/views/products/new.html.erb
<h1>Add a New Product</h1>

<%= link_to "Back", products_url %>

<p><%= render 'form' %></p>

app/views/products/show.html.erb
<div class="button"><%= link_to "< Back to Products", products_url %> <%= link_to "Edit Products", edit_product_url(@product) %> <%= link_to "Delete Product", @product, :confirm => "Are you sure you want to delete this product?", :method => :delete%></div>
    
<div id="review-form-errors">
  <%= render :partial => 'reviewerror' %>
</div>

<h1><%= @product[:name].upcase %></h1>

<div class="picture"><%= render 'image' %></div>

<div class="info">

<p>Description: <%= @product[:description] %></p>
<p>Price: $<%= @product.formatted_price %></p>

  <h3>Reviews</h3>

  <p>Reviews for <%= @product.name %></p>

    <div id="review-list">
      <p><%= render :partial => 'review' %></p>
    </div>

<% if current_user %>

  <h4> New Review </h4>

<div id="new_review">
  <p><%= render 'newreview' %></p>
</div>

  <h4> New Image </h4>

  <p><%= render 'newimage' %></p>

  <% else %>
    <p>Please <%= link_to "log in", new_session_path %> to add an image or review </p>    
<% end %>

</div>

<script type="text/javascript">
  $(function() {
     $("#new_review")
        .on('ajax:beforeSend', function() { 
          $("input[type='submit']") 
            .val('Saving...')
            .attr('disabled', 'disabled');
        })
        .on('ajax:complete', function() {
          $("input[type='submit']")
            .val('Create Review')
            .removeAttr('disabled');
        });
  });
</script>

app/views/reviews/create.js.erb
<% if @review.errors.present? %>
  $("#review-form-errors").html("<%= escape_javascript(render(:partial => '/products/reviewerror')) %>");
<% else %>
  $("#review-form-errors").html("");
  $("#review-list").html("<%= escape_javascript(render(:partial => '/products/review')) %>");
  $("#new_review")[0].reset();
<% end %>

app/views/reviews/edit.html.erb
<h1>Reviews#edit</h1>
<p>Find me in app/views/reviews/edit.html.erb</p>

app/views/reviews/new.html.erb
<h1>Reviews#new</h1>
<p>Find me in app/views/reviews/new.html.erb</p>

app/views/reviews/show.html.erb
<h1>Reviews#show</h1>
<p>Find me in app/views/reviews/show.html.erb</p>

app/views/users/edit.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %> 
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %> 
    <%= f.text_area :email %>
  </div>
  <div class="field">
    <%= f.label :avatar %>
    <%= f.file_field :avatar %>
  </div>
  <div class="actions">
    <br><%= f.submit %>
  </div>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<p><%= link_to "Back to Products Index", products_url %></p>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.label :avatar %>
    <%= f.file_field :avatar %>
  </div>

  <div class = "actions"><%= f.submit %></div>
  <% end %>

app/views/users/show.html.erb
<h1> User Profile </h1>

<%= link_to "Back to Products", products_url %> <%= link_to "Edit User", edit_user_url(@user) %> <%= link_to "Delete User", @user, :confirm => "Are you sure you want to delete this user?", :method => :delete%>

<p>Name: <%= @user[:name] %></p>
<p>Email: <%= @user[:email] %></p>
<%= image_tag (@user.avatar) %>